name: pic_viewer
description: Simple application for viewing pictures

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^5.0.2
  dio: ^5.0.1
  retrofit: ^4.0.1
  freezed_annotation: ^2.1.0
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  easy_localization: ^3.0.1
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  json_serializable: ^6.5.0
  freezed: ^2.3.2
  auto_route_generator: ^5.0.3 
  retrofit_generator: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
